### ISSUE TITLE
Not all icons were bundled during build (tested with fresh project)

### ISSUE THREAD

**Issue by claytonchew** [nuxt-ui-pro/docs#59] opened 2024-05-08 13:39 UTC
## Issue

Not all icons were bundled (missing) during build, some icons were missing when run on production.

![SCR-20240508-skjj](https://github.com/nuxt-ui-pro/docs/assets/30117799/97abc447-bf1c-4735-8651-048f542ddb23)

![SCR-20240508-sklb](https://github.com/nuxt-ui-pro/docs/assets/30117799/128e9385-3d2f-4c0c-96e9-283dbda43fdb)

![SCR-20240508-skrv](https://github.com/nuxt-ui-pro/docs/assets/30117799/97436bb8-8a36-4d56-8726-1d486d24556b)

## Outcome is the same with

❌  `npm run build` then `node .output/server/index.mjs` locally.
❌ docker build and run

## Reproduction

Start completely from fresh project

```
npx nuxi init -t github:nuxt-ui-pro/docs
```

Run build

```
npm run build
```

Run server locally

```
node .output/server/index.mjs
```

**Comment by claytonchew** [comment] 2024-05-09 16:12
Seems like it is resolved by having it built twice (one after the other).

```
npm run build
npm run build
```

**Comment by kingyue737** [comment] 2024-06-24 04:45
My workaround:
```
npm run prepare
npm run build 
```

**Comment by benjamincanac** [comment] 2024-07-11 08:40
Can we close this? Have you made sure to register the `@nuxt/content` before `@nuxt/ui`?

**Comment by kingyue737** [comment] 2024-07-11 08:47
I didn't touch the module orders. Official sites based on `nuxt-ui-pro/doc`s like `@nuxt/content` have the same issue:

![image](https://github.com/nuxt-ui-pro/docs/assets/40021217/95e656fb-6f23-41f1-be85-4e1e24d1793a)

**Comment by kingyue737** [comment] 2024-07-11 08:51
Nuxt Image:

![image](https://github.com/nuxt-ui-pro/docs/assets/40021217/d3a0ef84-44d8-42df-9b5c-7bd7856c1842)

**Comment by benjamincanac** [comment] 2024-07-11 08:54
Are you deploying on Cloudflare?

**Comment by kingyue737** [comment] 2024-07-11 09:05
Yes. I can also reproduce locally if I run `nuxi cleanup` before build. It will also show the following warning during build:
```
warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
warn - Update your configuration file to eliminate this warning.
warn - https://tailwindcss.com/docs/upgrade-guide#configure-content-sources
``` 

If I build another time with cache in `.nuxt`, this warning disappears and no issue occurs.

**Comment by benjamincanac** [comment] 2024-07-11 09:06
This is due to how the `@nuxtjs/tailwindcss` module works since https://github.com/nuxt-modules/tailwindcss/releases/tag/v6.12.0. We've been having lots of issues with this..

**Comment by kingyue737** [comment] 2024-07-11 09:31
Thanks for pointing out this. Maybe we can close this and track at https://github.com/nuxt-modules/tailwindcss/issues/855 ?

**Closed** 2024-07-11 10:16 UTC

**Comment by benjamincanac** [comment] 2024-07-11 14:52
As @kingyue737 mentioned, a `nuxt prepare` is required so you can add a `postinstall` script in your `package.json` like: https://github.com/nuxt-ui-pro/docs/blob/main/package.json#L10
